### PR TITLE
Add login and logout functionality, session management, and authentic…

### PR DESCRIPTION
**Pull request by spatiallyabsent**
…ation middleware

### CODE REVIEW

**Comment by spatiallyabsent** [comment]
looks good

**Review by spatiallyabsent — COMMENTED** [review]
looks good test

**Comment by spatiallyabsent** [comment]
test

**Review by mazoal1982 — COMMENTED** [review]
Great

**Review by Agerian — APPROVED** [review]
Looks good

**Review by mazoal1982 — APPROVED** [review]
Great

**Comment by mazoal1982** [comment]
Excellent

**Pull request merged**
